[package]
name = "apis"
version = "0.1.0"
authors = ["André Vennberg <andre.vennberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility = { path="../utility" }

log = "0.4"
bytes = "1"
hyper = "0.14"
regex = "1"
strum = "0.20"
anyhow = "1.0"
chrono = "0.4"
futures = "0.3"
itertools = "0.10"
once_cell = "1.7"
deepl-api = "0.2"
serde_json = "1"
openai-api = "0.1"
serde_with = "1.8"
async-trait = "0.1"
strum_macros = "0.20"
libretranslate = "0.5"
chrono-humanize = "0.2"
serde_path_to_error = "0.1"

tracing = "0.1"
tracing-futures = "0.2"

tokio = { version="1.2", features=["full"] }
serde = { version="1", features=["derive"] }
backoff = { version="0.3", features=["tokio"] }
reqwest = { version="0.11", features=["json", "stream", "blocking"] }
serenity = { version="0.10", default-features=false, features=[
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "utils",
    "rustls_backend",
    "framework",
    "standard_framework",
    "unstable_discord_api",
] }
