[package]
name = "holo-bot"
version = "0.1.0"
authors = ["anden3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.12"
bytes = "1.0.1"
chrono = "0.4.19"
chrono-humanize = "0.1.2"
serenity = { version = "0.10.2", default-features = false, features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "utils",
    "rustls_backend",
] }
serde_json = "1.0"
graphql_client = "0.9"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.2.0", features = ["full"] }
reqwest = { version = "0.11.1", features = ["json", "stream", "blocking"] }
