[package]
name = "holo-bot"
version = "1.0.0"
authors = ["anden3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
async-trait = "0.1.48"
futures = "0.3.12"
bytes = "1"
url = { version = "2", features = ["serde"] }
chrono = "0.4"
chrono-tz = "0.5"
chrono-humanize = "0.1"
serenity = { version = "0.10", default-features = false, features = [
	"builder",
	"cache",
	"client",
	"gateway",
	"model",
	"http",
	"utils",
	"rustls_backend",
	"framework",
	"standard_framework",
] }
serde_json = "1"
serde-hex = "0.1"
serde_with = "1.8"
graphql_client = "0.9"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.2", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream", "blocking"] }
rusqlite = { version = "0.24", features = ["chrono", "serde_json", "url"] }
openssl = { version = "0.10", features = ["vendored"] }
deepl-api = "0.2.0"
libretranslate = "0.2"
strum = "0.20"
strum_macros = "0.20"
cached = "0.23.0"
regex = "1.4.5"
lazy_static = "1.4.0"
crossterm = "0.19"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
rand = "0.8"
