[workspace]
members = [
    "crates/*",
    "crates/apis/mchad",
    "crates/apis/livetl",
    "crates/apis/twitter",
]

[profile.dev]
debug = 2
lto = "thin"
incremental = true

[profile.dev.package.backtrace]
opt-level = 3

[patch.crates-io]
songbird = { path = "../songbird" }
audiopus_sys = { path = "../audiopus_sys" }
