[package]
name = "utility"
version = "0.1.0"
authors = ["André Vennberg <andre.vennberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
strum = "0.20"
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.5"
serde-hex = "0.1"
num-traits = "0.2.14"
serde_json = "1"
strum_macros = "0.20"

url = { version = "2", features = ["serde"] }
fern = { version = "0.6", features = ["colored"] }
serde = { version = "1", features = ["derive"] }
rusqlite = { version = "0.25", features = ["chrono", "serde_json", "url"] }
serenity = { version = "0.10", default-features = false, features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "utils",
    "rustls_backend",
    "framework",
    "standard_framework",
    "unstable_discord_api",
] }
