[package]
name = "macros"
version = "0.1.0"
authors = ["anden3 <andre.vennberg@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", default-features = false, features = ["derive"] }
quote = "1"
proc-macro2 = "1"
