[package]
name = "macros"
version = "0.1.0"
authors = ["anden3 <andre.vennberg@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", default-features = false, features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"
