[package]
name = "deepl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130" }
ureq = { version = "2.3.0", features = ["json"] }
